[package]
name = "actrail-kv-receiver-bin"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "actrail-kv-receiver"
path = "src/main.rs"

[dependencies]
actrail-kv-receiver.workspace = true
anyhow.workspace = true
axum.workspace = true
clap.workspace = true
tokio.workspace = true

[lints]
workspace = true
