[package]
name = "actrail-kv-analyzer"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
actrail-kv-artifacts.workspace = true
anyhow.workspace = true
hex.workspace = true
serde.workspace = true
serde_json.workspace = true
same-file.workspace = true
sha2.workspace = true
tempfile.workspace = true
thiserror.workspace = true
time.workspace = true

[dev-dependencies]
proptest.workspace = true

[lints]
workspace = true
