[package]
name = "actrail-kv-reporter"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
actrail-kv-artifacts.workspace = true
anyhow.workspace = true
html-escape.workspace = true
serde_json.workspace = true
same-file.workspace = true
tempfile.workspace = true

[lints]
workspace = true
